# Generated by Django 5.0.4 on 2025-12-30 17:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='cv',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
