# Generated by Django 5.0.4 on 2025-12-30 17:53

from django.db import migrations
from django.contrib.auth.hashers import make_password

def seed_initial_data(apps, schema_editor):
    User = apps.get_model('jobapps', 'User')
    JobPost = apps.get_model('jobapps', 'JobPost')
    Applications = apps.get_model('jobapps', 'Applications')

    # ===== USERS =====

    employer = User.objects.create(
        username='employer1',
        password=make_password('123456'),
        role='employer',
        is_active=True
    )

    candidate = User.objects.create(
        username='candidate1',
        password=make_password('123456'),
        role='candidate',
        is_active=True
    )

    # ===== JOB POSTS =====
    job1 = JobPost.objects.create(
        employer=employer,
        name='Backend Developer',
        company='OpenAI',
        description='Django REST API',
        request='2 năm Django',
        salary=2000,
        address='Hà Nội',
        benefits='Remote, Bonus'
    )

    job2 = JobPost.objects.create(
        employer=employer,
        name='Frontend Developer',
        company='Google',
        description='ReactJS',
        request='1 năm React',
        salary=1800,
        address='TP HCM',
        benefits='Laptop, BHXH'
    )

    # ===== APPLICATION =====
    Applications.objects.create(
        job_post=job1,
        candidate=candidate,
        notes='Ứng tuyển vị trí Frontend Developer',
        applied='CV gửi qua hệ thống',
        cv='image/upload/v1767117519/alzt5otwbcwlmiiy4zkm.png'
    )

    Applications.objects.create(
        job_post=job2,
        candidate=candidate,
        notes='Ứng tuyển vị trí Backend',
        applied='CV gửi qua hệ thống',
        cv='image/upload/v1767117535/mvxdzkxwh4hhwtomx8tj.png'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0003_alter_applications_cv'),
    ]

    operations = [
        migrations.RunPython(seed_initial_data),
    ]
