# Generated by Django 5.0.4 on 2026-01-05 10:04
from django.db import migrations
from django.contrib.auth.hashers import make_password
import random

def seed_initial_data(apps, schema_editor):
    User = apps.get_model('jobapps', 'User')
    Category = apps.get_model('jobapps', 'Category')
    JobPost = apps.get_model('jobapps', 'JobPost')
    Applications = apps.get_model('jobapps', 'Applications')

    # ================= 1. CATEGORIES =================
    categories_names = ['Công nghệ thông tin', 'Kinh doanh', 'Marketing', 'Kế toán', 'Ngôn ngữ', 'Thiết kế', 'Y tế']
    categories = []
    for name in categories_names:
        cat, _ = Category.objects.get_or_create(name=name)
        categories.append(cat)

    # ================= 2. USERS (Tạo thêm user để data đa dạng) =================
    employers = []
    candidates = []

    for i in range(1, 5): # Tạo 4 employers
        user, _ = User.objects.get_or_create(
            username=f'employer{i}',
            defaults={
                'password': make_password('123'),
                'role': 'employer',
                'is_active': True
            }
        )
        employers.append(user)

    for i in range(1, 6): # Tạo 5 candidates
        user, _ = User.objects.get_or_create(
            username=f'candidate{i}',
            defaults={
                'password': make_password('123'),
                'role': 'candidate',
                'is_active': True
            }
        )
        candidates.append(user)

    # ================= 3. JOB POSTS (Tăng lên 15 bài) =================
    job_titles = [
        'Backend Developer (Python/Django)', 'Frontend Developer (React)',
        'Mobile Developer (React Native)', 'AI Engineer (Machine Learning)',
        'Data Scientist', 'DevOps Engineer', 'UI/UX Designer',
        'Project Manager', 'Business Analyst', 'Digital Marketing Specialist',
        'Senior Accountant', 'English Teacher', 'Sales Executive',
        'Software Tester (QA)', 'Cloud Architect'
    ]

    job_posts = []
    for i, title in enumerate(job_titles):
        # Sử dụng update_or_create hoặc kiểm tra tồn tại để tránh lỗi trùng lặp khi chạy lại
        job, created = JobPost.objects.get_or_create(
            name=title,
            company=f'Tập đoàn Công nghệ {i + 1}', # Thêm thuộc tính này vào lookup để tránh trùng tên Job nhưng khác công ty
            defaults={
                'employer': random.choice(employers),
                'category': random.choice(categories),
                'description': f'Mô tả chi tiết công việc cho vị trí {title}. Chúng tôi tìm kiếm ứng viên năng động.',
                'request': 'Kinh nghiệm tối thiểu 2 năm, thái độ tốt.',
                'salary': random.randint(15000000, 50000000), # Để số tiền thực tế hơn
                'address': random.choice(['Hà Nội', 'TP HCM', 'Đà Nẵng', 'Cần Thơ']),
                'benefits': 'Lương tháng 13, Bảo hiểm PVI, Du lịch hàng năm',
                'active': True
            }
        )
        job_posts.append(job)

    # ================= 4. APPLICATIONS (Tạo ngẫu nhiên đơn ứng tuyển) =================
    cv_images = [
        'image/upload/v1767117519/alzt5otwbcwlmiiy4zkm.png',
        'image/upload/v1767117535/mvxdzkxwh4hhwtomx8tj.png',
    ]

    # Mỗi Job sẽ có từ 1 đến 2 người ứng tuyển ngẫu nhiên
    for job in job_posts:
        applied_candidates = random.sample(candidates, random.randint(1, 2))
        for cand in applied_candidates:
            Applications.objects.get_or_create(
                job_post=job,
                candidate=cand,
                defaults={
                    'full_name': cand.username.capitalize(),
                    'email': f'{cand.username}@gmail.com',
                    'phone': f'090{random.randint(1000000, 9999999)}',
                    'cv': random.choice(cv_images),
                    'active': True
                }
            )

class Migration(migrations.Migration):
    dependencies = [
        ('jobapps', '0004_category_alter_applications_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_initial_data),
    ]