# Generated by Django 5.0.4 on 2026-01-02 13:27

from django.db import migrations
from django.contrib.auth.hashers import make_password
import random


def seed_initial_data(apps, schema_editor):
    User = apps.get_model('jobapps', 'User')
    JobPost = apps.get_model('jobapps', 'JobPost')
    Applications = apps.get_model('jobapps', 'Applications')

    # ================= USERS =================
    employers = []
    candidates = []

    for i in range(1, 3):  # 2 employers
        user, _ = User.objects.get_or_create(
            username=f'employer{i}',
            defaults={
                'password': make_password('123'),
                'role': 'employer',
                'is_active': True
            }
        )
        employers.append(user)

    for i in range(1, 3):  # 2 candidates
        user, _ = User.objects.get_or_create(
            username=f'candidate{i}',
            defaults={
                'password': make_password('123'),
                'role': 'candidate',
                'is_active': True
            }
        )
        candidates.append(user)

    # ================= JOB POSTS =================
    job_titles = [
        'Backend Developer', 'Frontend Developer', 'Fullstack Developer',
        'Mobile Developer', 'DevOps Engineer', 'Data Engineer',
        'AI Engineer', 'QA Engineer', 'System Admin',
        'React Native Developer', 'Django Developer',
        'Java Developer', 'PHP Developer',
        'Python Developer', 'NodeJS Developer'
    ]

    job_posts = []

    for i, title in enumerate(job_titles):
        job, _ = JobPost.objects.get_or_create(
            name=title,
            defaults={
                'employer': random.choice(employers),
                'company': f'Company {i + 1}',
                'description': f'Mô tả công việc cho {title}',
                'request': 'Có kinh nghiệm từ 1–3 năm',
                'salary': random.randint(1000, 3000),
                'address': random.choice(['Hà Nội', 'TP HCM', 'Đà Nẵng']),
                'benefits': 'Thưởng, Remote, BHXH'
            }
        )
        job_posts.append(job)

    # ================= APPLICATIONS =================
    cv_images = [
        'image/upload/v1767117519/alzt5otwbcwlmiiy4zkm.png',
        'image/upload/v1767117535/mvxdzkxwh4hhwtomx8tj.png',
    ]

    for job in job_posts:
        Applications.objects.get_or_create(
            job_post=job,
            candidate=random.choice(candidates),
            defaults={
                'full_name': 'Nguyễn Văn A',
                'email': 'candidate@example.com',
                'phone': '0123456789',
                'cv': random.choice(cv_images)
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0006_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_initial_data),
    ]



