# Generated by Django 5.0.4 on 2026-01-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0007_seed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
