# Generated by Django 5.0.4 on 2026-01-02 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0008_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobapps.jobpost'),
        ),
    ]
